language: ruby
cache: bundler
rvm:
 - 2.3.0
jdk:
 - oraclejdk8
script:
 - bundle exec rake speccop rubocop
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "gem install bundler"
 - "RAILS_ENV=test rake db:setup"
branches:
 only:
   - master
   - staging
   - develop
   - /^(?i:release).*$/
addons:
 postgresql: "9.3"
services:
 - postgresql